ls:
  .auto.tfvars: kebab-case
  .hcl: kebab-case
  .tf: kebab-case
  .tf.json: kebab-case
  .tfstate: kebab-case
  .tftest.hcl: kebab-case
  .tfvars: kebab-case
  .tfvars.json: kebab-case

ignore:
  - .git
  - .github
  - .ls-lint.yaml
  - .terraform
  - .terraform.lock.hcl
  - .tflint.hcl
  - examples
  - node_modules
