formatter: markdown table

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

header-from: main.tf

content: |-
  {{ .Header }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
  {{ .Requirements }}
  {{ .Footer }}

sections:
  hide: [modules, providers]

recursive:
  enabled: false

settings:
  anchor: false
  color: false
  default: true
  description: true
  escape: true
  hide-empty: true
  html: false
  indent: 0
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

sort:
  by: required
  enabled: true
