name: ci

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read
  packages: read

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  context:
    uses: escapace/workflows/.github/workflows/context.yaml@trunk

  ci:
    needs:
      - context
    uses: escapace/workflows/.github/workflows/ci-terraform-module.yaml@trunk
    with:
      ref: ${{ needs.context.outputs.ref }}
      version: ${{ needs.context.outputs.version }}

      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      terraform-version: ${{ needs.context.outputs.terraform-version }}
      tflint-version: ${{ needs.context.outputs.tflint-version }}
      trivy-version: ${{ needs.context.outputs.trivy-version }}
